name: Hello

on: 
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./hello-world-docker-action/action.yml
        with:
            who-to-greet: 'Felipe'
